version: '3.8'

services:
  my_database:
    image: mysql:latest
    container_name: DB
    environment:
      MYSQL_DATABASE: JUGADORES
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - fastapi_db_data:/var/lib/mysql
    networks:
      - skainet

networks:
  skainet:
    driver: bridge

volumes:
  fastapi_db_data:
